Minimal stride argument checking
team-charls/charls pull request #101
Opened 2021-10-01 13:11 UTC by malaterre

2021-10-01 13:12 UTC, malaterre commented
@vbaderks Here is the typical user error:

```
#include <charls/charls.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

int main(int argc, char * argv[])
{
  charls_frame_info frame_info = {.width = 512, .height = 512, .bits_per_sample = 8, .component_count = 3};
  size_t input_size =  frame_info.width * frame_info.height * frame_info.component_count;
  void* input = malloc(input_size);
  memset(input, 0, input_size);

  charls_jpegls_encoder* encoder = charls_jpegls_encoder_create();
  charls_jpegls_errc error = charls_jpegls_encoder_set_frame_info(encoder, &frame_info);
  charls_interleave_mode interleave_mode;
  interleave_mode = CHARLS_INTERLEAVE_MODE_NONE; // not ok
  // interleave_mode = CHARLS_INTERLEAVE_MODE_SAMPLE; // ok
  error = charls_jpegls_encoder_set_interleave_mode(encoder, interleave_mode);
  size_t encoded_buffer_size;
  error = charls_jpegls_encoder_get_estimated_destination_size(encoder, &encoded_buffer_size);

  void* encoded_buffer = malloc(encoded_buffer_size);
  error = charls_jpegls_encoder_set_destination_buffer(encoder, encoded_buffer, encoded_buffer_size);
  error = charls_jpegls_encoder_encode_from_buffer(encoder, input, input_size, input_size / frame_info.height ); // <- bogus stride
  size_t bytes_written;
  error = charls_jpegls_encoder_get_bytes_written(encoder, &bytes_written);
 
  charls_jpegls_encoder_destroy(encoder);
  free(encoded_buffer);
  free(input);

  fprintf(stdout, "success\n" );
  return 0;
}
```

2021-10-02 13:15 UTC, vbaderks requested changes
- Would it be possible to move lines to helper function "check_stride"?
- Make it an else of (stride == 0). If stride is computed, there is no need to check.

2021-11-11 20:29 UTC, vbaderks commented
I have updated and extended the unit tests for your PR, but not finished yet. Is on the to-do list.

2021-11-15 23:20 UTC, vbaderks approved these changes

2021-11-15 23:24 UTC, merged